name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Sanity Check
      id: sanity-check
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Sanity Check
        setup-command: npm install
        command: npm test -i src/sanity.test.ts
        timeout: 10
        max-score: 50
    - name: Count
      id: count
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Count
        setup-command: npm install
        command: npm test count
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SANITY-CHECK_RESULTS: "${{steps.sanity-check.outputs.result}}"
        COUNT_RESULTS: "${{steps.count.outputs.result}}"
      with:
        runners: sanity-check,count
